Job started
Traceback (most recent call last):
  File "dist1.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "dist1.py", line 5, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62188,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Job completed
